version: 0.2

phases:
  install:
    commands:
      - npm install yarn -g
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 sync build/ s3://socialaggregatorweb/www/