version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
      
  post_build:
    commands:
      - mkdir output
      - mv index.html static/ output
      - aws s3 sync output/ s3://socialaggregatorweb/www/
artifacts:
  files:
    - '**/*'
  base-directory: 'output'
  discard-paths: no